blank_issues_enabled: false
contact_links:
  - name: Designs / Discussions / Proposals
    url: https://www.notion.so/keyring/Product-Management-95577139ae614d3085c7d9397aadea46
    about: We use Notion for this purpose.